import {
  ArrowLeft,
  ArrowRight,
  Banknote,
  Check,
  ChevronDown,
  ClipboardList,
  Clock3,
  Grid2X2,
  Heart,
  House,
  Loader2,
  LogOut,
  Map,
  Minus,
  Package,
  Plus,
  Search,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Tag,
  TriangleAlert,
  User,
  Utensils,
  X,
  Zap,
} from "lucide-react-native";
import { theme } from "../theme";

// Merged icon mapper — union of the web MarketplaceIcon + SellerIcon maps.
const ICONS = {
  arrowRight: ArrowRight,
  bag: ShoppingBag,
  bolt: Zap,
  chevron: ChevronDown,
  food: Utensils,
  grid: Grid2X2,
  heart: Heart,
  home: House,
  map: Map,
  phone: Smartphone,
  search: Search,
  shield: ShieldCheck,
  shirt: Shirt,
  spark: Sparkles,
  star: Star,
  store: Store,
  tag: Tag,
  package: Package,
  plus: Plus,
  arrowLeft: ArrowLeft,
  logout: LogOut,
  warning: TriangleAlert,
  money: Banknote,
  clock: Clock3,
  orders: ClipboardList,
  dashboard: Grid2X2,
  products: Package,
  user: User,
  close: X,
  minus: Minus,
  check: Check,
  loader: Loader2,
};

export default function Icon({ name, size = 18, strokeWidth = 1.9, color, ...props }) {
  const Cmp = ICONS[name] || Sparkles;
  return <Cmp size={size} strokeWidth={strokeWidth} color={color || theme.colors.ink} {...props} />;
}
